# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'majiang.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1321, 879)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.playerOne = QtWidgets.QFrame(Dialog)
        self.playerOne.setGeometry(QtCore.QRect(10, 70, 471, 81))
        self.playerOne.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerOne.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerOne.setObjectName("playerOne")
        self.label_2 = QtWidgets.QLabel(self.playerOne)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.playerOneText = QtWidgets.QPlainTextEdit(self.playerOne)
        self.playerOneText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerOneText.setObjectName("playerOneText")
        self.playerOneaddBtn = QtWidgets.QPushButton(self.playerOne)
        self.playerOneaddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerOneaddBtn.setObjectName("playerOneaddBtn")
        self.playerOneClearBtn = QtWidgets.QPushButton(self.playerOne)
        self.playerOneClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerOneClearBtn.setObjectName("playerOneClearBtn")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(540, 60, 681, 641))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 22, 77, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1W = QtWidgets.QLabel(self.layoutWidget)
        self.label_1W.setObjectName("label_1W")
        self.verticalLayout.addWidget(self.label_1W)
        self.pushButton_1W = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_1W.setObjectName("pushButton_1W")
        self.verticalLayout.addWidget(self.pushButton_1W)
        self.label_2W = QtWidgets.QLabel(self.groupBox)
        self.label_2W.setGeometry(QtCore.QRect(110, 24, 69, 80))
        self.label_2W.setObjectName("label_2W")
        self.pushButton_2W = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2W.setGeometry(QtCore.QRect(110, 110, 69, 23))
        self.pushButton_2W.setObjectName("pushButton_2W")
        self.label_3W = QtWidgets.QLabel(self.groupBox)
        self.label_3W.setGeometry(QtCore.QRect(210, 24, 69, 80))
        self.label_3W.setObjectName("label_3W")
        self.pushButton_3W = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3W.setGeometry(QtCore.QRect(210, 110, 69, 23))
        self.pushButton_3W.setObjectName("pushButton_3W")
        self.label_4W = QtWidgets.QLabel(self.groupBox)
        self.label_4W.setGeometry(QtCore.QRect(310, 24, 69, 80))
        self.label_4W.setObjectName("label_4W")
        self.pushButton_4W = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4W.setGeometry(QtCore.QRect(310, 110, 69, 23))
        self.pushButton_4W.setObjectName("pushButton_4W")
        self.label_5W = QtWidgets.QLabel(self.groupBox)
        self.label_5W.setGeometry(QtCore.QRect(410, 24, 69, 80))
        self.label_5W.setObjectName("label_5W")
        self.pushButton_5W = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5W.setGeometry(QtCore.QRect(410, 110, 69, 23))
        self.pushButton_5W.setObjectName("pushButton_5W")
        self.label_6W = QtWidgets.QLabel(self.groupBox)
        self.label_6W.setGeometry(QtCore.QRect(510, 24, 69, 80))
        self.label_6W.setObjectName("label_6W")
        self.pushButton_6W = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6W.setGeometry(QtCore.QRect(510, 110, 69, 23))
        self.pushButton_6W.setObjectName("pushButton_6W")
        self.label_7W = QtWidgets.QLabel(self.groupBox)
        self.label_7W.setGeometry(QtCore.QRect(610, 24, 69, 80))
        self.label_7W.setObjectName("label_7W")
        self.pushButton_7W = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7W.setGeometry(QtCore.QRect(610, 110, 69, 23))
        self.pushButton_7W.setObjectName("pushButton_7W")
        self.label_8W = QtWidgets.QLabel(self.groupBox)
        self.label_8W.setGeometry(QtCore.QRect(10, 134, 69, 80))
        self.label_8W.setObjectName("label_8W")
        self.pushButton_8W = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8W.setGeometry(QtCore.QRect(10, 220, 69, 23))
        self.pushButton_8W.setObjectName("pushButton_8W")
        self.label_9W = QtWidgets.QLabel(self.groupBox)
        self.label_9W.setGeometry(QtCore.QRect(110, 134, 69, 80))
        self.label_9W.setObjectName("label_9W")
        self.pushButton_9W = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9W.setGeometry(QtCore.QRect(110, 220, 69, 23))
        self.pushButton_9W.setObjectName("pushButton_9W")
        self.label_1T = QtWidgets.QLabel(self.groupBox)
        self.label_1T.setGeometry(QtCore.QRect(210, 134, 69, 80))
        self.label_1T.setObjectName("label_1T")
        self.pushButton_1T = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_1T.setGeometry(QtCore.QRect(210, 220, 69, 23))
        self.pushButton_1T.setObjectName("pushButton_1T")
        self.label_2T = QtWidgets.QLabel(self.groupBox)
        self.label_2T.setGeometry(QtCore.QRect(310, 134, 69, 80))
        self.label_2T.setObjectName("label_2T")
        self.pushButton_2T = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2T.setGeometry(QtCore.QRect(310, 220, 69, 23))
        self.pushButton_2T.setObjectName("pushButton_2T")
        self.label_3T = QtWidgets.QLabel(self.groupBox)
        self.label_3T.setGeometry(QtCore.QRect(410, 134, 69, 80))
        self.label_3T.setObjectName("label_3T")
        self.pushButton_3T = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3T.setGeometry(QtCore.QRect(410, 220, 69, 23))
        self.pushButton_3T.setObjectName("pushButton_3T")
        self.label_4T = QtWidgets.QLabel(self.groupBox)
        self.label_4T.setGeometry(QtCore.QRect(510, 134, 69, 80))
        self.label_4T.setObjectName("label_4T")
        self.pushButton_4T = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4T.setGeometry(QtCore.QRect(510, 220, 69, 23))
        self.pushButton_4T.setObjectName("pushButton_4T")
        self.label_5T = QtWidgets.QLabel(self.groupBox)
        self.label_5T.setGeometry(QtCore.QRect(610, 134, 69, 80))
        self.label_5T.setObjectName("label_5T")
        self.pushButton_5T = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5T.setGeometry(QtCore.QRect(610, 220, 69, 23))
        self.pushButton_5T.setObjectName("pushButton_5T")
        self.pushButton_6T = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6T.setGeometry(QtCore.QRect(10, 346, 69, 23))
        self.pushButton_6T.setObjectName("pushButton_6T")
        self.label_6T = QtWidgets.QLabel(self.groupBox)
        self.label_6T.setGeometry(QtCore.QRect(10, 260, 69, 80))
        self.label_6T.setObjectName("label_6T")
        self.pushButton_7T = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7T.setGeometry(QtCore.QRect(110, 346, 69, 23))
        self.pushButton_7T.setObjectName("pushButton_7T")
        self.label_7T = QtWidgets.QLabel(self.groupBox)
        self.label_7T.setGeometry(QtCore.QRect(110, 260, 69, 80))
        self.label_7T.setObjectName("label_7T")
        self.pushButton_8T = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8T.setGeometry(QtCore.QRect(210, 346, 69, 23))
        self.pushButton_8T.setObjectName("pushButton_8T")
        self.label_8T = QtWidgets.QLabel(self.groupBox)
        self.label_8T.setGeometry(QtCore.QRect(210, 260, 69, 80))
        self.label_8T.setObjectName("label_8T")
        self.pushButton_9T = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9T.setGeometry(QtCore.QRect(310, 346, 69, 23))
        self.pushButton_9T.setObjectName("pushButton_9T")
        self.label_9T = QtWidgets.QLabel(self.groupBox)
        self.label_9T.setGeometry(QtCore.QRect(310, 260, 69, 80))
        self.label_9T.setObjectName("label_9T")
        self.pushButton_1sou = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_1sou.setGeometry(QtCore.QRect(410, 346, 69, 23))
        self.pushButton_1sou.setObjectName("pushButton_1sou")
        self.label_1sou = QtWidgets.QLabel(self.groupBox)
        self.label_1sou.setGeometry(QtCore.QRect(410, 260, 69, 80))
        self.label_1sou.setObjectName("label_1sou")
        self.label_2sou = QtWidgets.QLabel(self.groupBox)
        self.label_2sou.setGeometry(QtCore.QRect(510, 260, 69, 80))
        self.label_2sou.setObjectName("label_2sou")
        self.pushButton_2sou = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2sou.setGeometry(QtCore.QRect(510, 346, 69, 23))
        self.pushButton_2sou.setObjectName("pushButton_2sou")
        self.pushButton_3sou = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3sou.setGeometry(QtCore.QRect(610, 346, 69, 23))
        self.pushButton_3sou.setObjectName("pushButton_3sou")
        self.label_3sou = QtWidgets.QLabel(self.groupBox)
        self.label_3sou.setGeometry(QtCore.QRect(610, 260, 69, 80))
        self.label_3sou.setObjectName("label_3sou")
        self.pushButton_4sou = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4sou.setGeometry(QtCore.QRect(10, 476, 69, 23))
        self.pushButton_4sou.setObjectName("pushButton_4sou")
        self.label_4sou = QtWidgets.QLabel(self.groupBox)
        self.label_4sou.setGeometry(QtCore.QRect(10, 390, 69, 80))
        self.label_4sou.setObjectName("label_4sou")
        self.pushButton_5sou = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5sou.setGeometry(QtCore.QRect(110, 476, 69, 23))
        self.pushButton_5sou.setObjectName("pushButton_5sou")
        self.label_5sou = QtWidgets.QLabel(self.groupBox)
        self.label_5sou.setGeometry(QtCore.QRect(110, 390, 69, 80))
        self.label_5sou.setObjectName("label_5sou")
        self.pushButton_6sou = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6sou.setGeometry(QtCore.QRect(210, 476, 69, 23))
        self.pushButton_6sou.setObjectName("pushButton_6sou")
        self.label_6sou = QtWidgets.QLabel(self.groupBox)
        self.label_6sou.setGeometry(QtCore.QRect(210, 390, 69, 80))
        self.label_6sou.setObjectName("label_6sou")
        self.pushButton_7sou = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7sou.setGeometry(QtCore.QRect(310, 476, 69, 23))
        self.pushButton_7sou.setObjectName("pushButton_7sou")
        self.label_7sou = QtWidgets.QLabel(self.groupBox)
        self.label_7sou.setGeometry(QtCore.QRect(310, 390, 69, 80))
        self.label_7sou.setObjectName("label_7sou")
        self.label_8sou = QtWidgets.QLabel(self.groupBox)
        self.label_8sou.setGeometry(QtCore.QRect(410, 390, 69, 80))
        self.label_8sou.setObjectName("label_8sou")
        self.pushButton_8sou = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8sou.setGeometry(QtCore.QRect(410, 476, 69, 23))
        self.pushButton_8sou.setObjectName("pushButton_8sou")
        self.pushButton_9sou = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9sou.setGeometry(QtCore.QRect(510, 476, 69, 23))
        self.pushButton_9sou.setObjectName("pushButton_9sou")
        self.label_9sou = QtWidgets.QLabel(self.groupBox)
        self.label_9sou.setGeometry(QtCore.QRect(510, 390, 69, 80))
        self.label_9sou.setObjectName("label_9sou")
        self.label_HZ = QtWidgets.QLabel(self.groupBox)
        self.label_HZ.setGeometry(QtCore.QRect(610, 390, 69, 80))
        self.label_HZ.setObjectName("label_HZ")
        self.pushButton_HZ = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_HZ.setGeometry(QtCore.QRect(610, 476, 69, 23))
        self.pushButton_HZ.setObjectName("pushButton_HZ")
        self.pushButton_Dong = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Dong.setGeometry(QtCore.QRect(10, 606, 69, 23))
        self.pushButton_Dong.setObjectName("pushButton_Dong")
        self.label_Dong = QtWidgets.QLabel(self.groupBox)
        self.label_Dong.setGeometry(QtCore.QRect(10, 520, 69, 80))
        self.label_Dong.setObjectName("label_Dong")
        self.pushButton_Xi = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Xi.setGeometry(QtCore.QRect(110, 606, 69, 23))
        self.pushButton_Xi.setObjectName("pushButton_Xi")
        self.label_Xi = QtWidgets.QLabel(self.groupBox)
        self.label_Xi.setGeometry(QtCore.QRect(110, 520, 69, 80))
        self.label_Xi.setObjectName("label_Xi")
        self.label_Nan = QtWidgets.QLabel(self.groupBox)
        self.label_Nan.setGeometry(QtCore.QRect(210, 520, 69, 80))
        self.label_Nan.setObjectName("label_Nan")
        self.pushButton_Nan = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Nan.setGeometry(QtCore.QRect(210, 606, 69, 23))
        self.pushButton_Nan.setObjectName("pushButton_Nan")
        self.pushButton_Bei = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Bei.setGeometry(QtCore.QRect(310, 606, 69, 23))
        self.pushButton_Bei.setObjectName("pushButton_Bei")
        self.label_Bei = QtWidgets.QLabel(self.groupBox)
        self.label_Bei.setGeometry(QtCore.QRect(310, 520, 69, 80))
        self.label_Bei.setObjectName("label_Bei")
        self.pushButton_Fa = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Fa.setGeometry(QtCore.QRect(410, 606, 69, 23))
        self.pushButton_Fa.setObjectName("pushButton_Fa")
        self.label_Fa = QtWidgets.QLabel(self.groupBox)
        self.label_Fa.setGeometry(QtCore.QRect(410, 520, 69, 80))
        self.label_Fa.setObjectName("label_Fa")
        self.pushButton_Bai = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Bai.setGeometry(QtCore.QRect(510, 606, 69, 23))
        self.pushButton_Bai.setObjectName("pushButton_Bai")
        self.label_Bai = QtWidgets.QLabel(self.groupBox)
        self.label_Bai.setGeometry(QtCore.QRect(510, 520, 69, 80))
        self.label_Bai.setObjectName("label_Bai")
        self.playerTow = QtWidgets.QFrame(Dialog)
        self.playerTow.setGeometry(QtCore.QRect(10, 170, 471, 81))
        self.playerTow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerTow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerTow.setObjectName("playerTow")
        self.label_3 = QtWidgets.QLabel(self.playerTow)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_3.setObjectName("label_3")
        self.playerTowText = QtWidgets.QPlainTextEdit(self.playerTow)
        self.playerTowText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerTowText.setObjectName("playerTowText")
        self.playerTowaddBtn = QtWidgets.QPushButton(self.playerTow)
        self.playerTowaddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerTowaddBtn.setObjectName("playerTowaddBtn")
        self.playerTowClearBtn = QtWidgets.QPushButton(self.playerTow)
        self.playerTowClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerTowClearBtn.setObjectName("playerTowClearBtn")
        self.playerThree = QtWidgets.QFrame(Dialog)
        self.playerThree.setGeometry(QtCore.QRect(10, 270, 471, 81))
        self.playerThree.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerThree.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerThree.setObjectName("playerThree")
        self.label_4 = QtWidgets.QLabel(self.playerThree)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_4.setObjectName("label_4")
        self.playerThreeText = QtWidgets.QPlainTextEdit(self.playerThree)
        self.playerThreeText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerThreeText.setObjectName("playerThreeText")
        self.playerThreeaddBtn = QtWidgets.QPushButton(self.playerThree)
        self.playerThreeaddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerThreeaddBtn.setObjectName("playerThreeaddBtn")
        self.playerThreeClearBtn = QtWidgets.QPushButton(self.playerThree)
        self.playerThreeClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerThreeClearBtn.setObjectName("playerThreeClearBtn")
        self.playerFour = QtWidgets.QFrame(Dialog)
        self.playerFour.setGeometry(QtCore.QRect(10, 370, 471, 81))
        self.playerFour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerFour.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerFour.setObjectName("playerFour")
        self.label_5 = QtWidgets.QLabel(self.playerFour)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_5.setObjectName("label_5")
        self.playerFourText = QtWidgets.QPlainTextEdit(self.playerFour)
        self.playerFourText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerFourText.setObjectName("playerFourText")
        self.playerFouraddBtn = QtWidgets.QPushButton(self.playerFour)
        self.playerFouraddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerFouraddBtn.setObjectName("playerFouraddBtn")
        self.playerFourClearBtn = QtWidgets.QPushButton(self.playerFour)
        self.playerFourClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerFourClearBtn.setObjectName("playerFourClearBtn")
        self.dunCard = QtWidgets.QFrame(Dialog)
        self.dunCard.setGeometry(QtCore.QRect(10, 470, 471, 81))
        self.dunCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dunCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dunCard.setObjectName("dunCard")
        self.label_7 = QtWidgets.QLabel(self.dunCard)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_7.setObjectName("label_7")
        self.dunText = QtWidgets.QPlainTextEdit(self.dunCard)
        self.dunText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.dunText.setObjectName("dunText")
        self.dunAddCard = QtWidgets.QPushButton(self.dunCard)
        self.dunAddCard.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.dunAddCard.setObjectName("dunAddCard")
        self.dunClear = QtWidgets.QPushButton(self.dunCard)
        self.dunClear.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.dunClear.setObjectName("dunClear")
        self.saveBtn = QtWidgets.QPushButton(Dialog)
        self.saveBtn.setGeometry(QtCore.QRect(450, 730, 161, 51))
        self.saveBtn.setObjectName("saveBtn")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 88, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.playerComboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.playerComboBox.setObjectName("playerComboBox")
        self.playerComboBox.addItem("")
        self.playerComboBox.addItem("")
        self.playerComboBox.addItem("")
        self.horizontalLayout.addWidget(self.playerComboBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "确认"))
        self.label_2.setText(_translate("Dialog", "玩家一"))
        self.playerOneaddBtn.setText(_translate("Dialog", "添加"))
        self.playerOneClearBtn.setText(_translate("Dialog", "重置"))
        self.groupBox.setTitle(_translate("Dialog", "牌型列表"))
        self.label_1W.setText(_translate("Dialog", "1W"))
        self.pushButton_1W.setText(_translate("Dialog", "+"))
        self.label_2W.setText(_translate("Dialog", "2W"))
        self.pushButton_2W.setText(_translate("Dialog", "+"))
        self.label_3W.setText(_translate("Dialog", "3W"))
        self.pushButton_3W.setText(_translate("Dialog", "+"))
        self.label_4W.setText(_translate("Dialog", "4W"))
        self.pushButton_4W.setText(_translate("Dialog", "+"))
        self.label_5W.setText(_translate("Dialog", "5W"))
        self.pushButton_5W.setText(_translate("Dialog", "+"))
        self.label_6W.setText(_translate("Dialog", "6W"))
        self.pushButton_6W.setText(_translate("Dialog", "+"))
        self.label_7W.setText(_translate("Dialog", "7W"))
        self.pushButton_7W.setText(_translate("Dialog", "+"))
        self.label_8W.setText(_translate("Dialog", "8W"))
        self.pushButton_8W.setText(_translate("Dialog", "+"))
        self.label_9W.setText(_translate("Dialog", "9W"))
        self.pushButton_9W.setText(_translate("Dialog", "+"))
        self.label_1T.setText(_translate("Dialog", "1T"))
        self.pushButton_1T.setText(_translate("Dialog", "+"))
        self.label_2T.setText(_translate("Dialog", "2T"))
        self.pushButton_2T.setText(_translate("Dialog", "+"))
        self.label_3T.setText(_translate("Dialog", "3T"))
        self.pushButton_3T.setText(_translate("Dialog", "+"))
        self.label_4T.setText(_translate("Dialog", "4T"))
        self.pushButton_4T.setText(_translate("Dialog", "+"))
        self.label_5T.setText(_translate("Dialog", "5T"))
        self.pushButton_5T.setText(_translate("Dialog", "+"))
        self.pushButton_6T.setText(_translate("Dialog", "+"))
        self.label_6T.setText(_translate("Dialog", "6T"))
        self.pushButton_7T.setText(_translate("Dialog", "+"))
        self.label_7T.setText(_translate("Dialog", "7T"))
        self.pushButton_8T.setText(_translate("Dialog", "+"))
        self.label_8T.setText(_translate("Dialog", "8T"))
        self.pushButton_9T.setText(_translate("Dialog", "+"))
        self.label_9T.setText(_translate("Dialog", "9T"))
        self.pushButton_1sou.setText(_translate("Dialog", "+"))
        self.label_1sou.setText(_translate("Dialog", "1S"))
        self.label_2sou.setText(_translate("Dialog", "2S"))
        self.pushButton_2sou.setText(_translate("Dialog", "+"))
        self.pushButton_3sou.setText(_translate("Dialog", "+"))
        self.label_3sou.setText(_translate("Dialog", "3S"))
        self.pushButton_4sou.setText(_translate("Dialog", "+"))
        self.label_4sou.setText(_translate("Dialog", "4S"))
        self.pushButton_5sou.setText(_translate("Dialog", "+"))
        self.label_5sou.setText(_translate("Dialog", "5S"))
        self.pushButton_6sou.setText(_translate("Dialog", "+"))
        self.label_6sou.setText(_translate("Dialog", "6S"))
        self.pushButton_7sou.setText(_translate("Dialog", "+"))
        self.label_7sou.setText(_translate("Dialog", "7S"))
        self.label_8sou.setText(_translate("Dialog", "8S"))
        self.pushButton_8sou.setText(_translate("Dialog", "+"))
        self.pushButton_9sou.setText(_translate("Dialog", "+"))
        self.label_9sou.setText(_translate("Dialog", "9S"))
        self.label_HZ.setText(_translate("Dialog", "HZ"))
        self.pushButton_HZ.setText(_translate("Dialog", "+"))
        self.pushButton_Dong.setText(_translate("Dialog", "+"))
        self.label_Dong.setText(_translate("Dialog", "Dong"))
        self.pushButton_Xi.setText(_translate("Dialog", "+"))
        self.label_Xi.setText(_translate("Dialog", "Xi"))
        self.label_Nan.setText(_translate("Dialog", "Nan"))
        self.pushButton_Nan.setText(_translate("Dialog", "+"))
        self.pushButton_Bei.setText(_translate("Dialog", "+"))
        self.label_Bei.setText(_translate("Dialog", "Bei"))
        self.pushButton_Fa.setText(_translate("Dialog", "+"))
        self.label_Fa.setText(_translate("Dialog", "Fa"))
        self.pushButton_Bai.setText(_translate("Dialog", "+"))
        self.label_Bai.setText(_translate("Dialog", "Bai"))
        self.label_3.setText(_translate("Dialog", "玩家二"))
        self.playerTowaddBtn.setText(_translate("Dialog", "添加"))
        self.playerTowClearBtn.setText(_translate("Dialog", "重置"))
        self.label_4.setText(_translate("Dialog", "玩家三"))
        self.playerThreeaddBtn.setText(_translate("Dialog", "添加"))
        self.playerThreeClearBtn.setText(_translate("Dialog", "重置"))
        self.label_5.setText(_translate("Dialog", "玩家四"))
        self.playerFouraddBtn.setText(_translate("Dialog", "添加"))
        self.playerFourClearBtn.setText(_translate("Dialog", "重置"))
        self.label_7.setText(_translate("Dialog", "墩上牌数据"))
        self.dunAddCard.setText(_translate("Dialog", "添加"))
        self.dunClear.setText(_translate("Dialog", "重置"))
        self.saveBtn.setText(_translate("Dialog", "保   存"))
        self.label.setText(_translate("Dialog", "游戏人数"))
        self.playerComboBox.setItemText(0, _translate("Dialog", "4"))
        self.playerComboBox.setItemText(1, _translate("Dialog", "3"))
        self.playerComboBox.setItemText(2, _translate("Dialog", "2"))

