# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paohuzi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1204, 822)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 88, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.AckBtn = QtWidgets.QPushButton(Dialog)
        self.AckBtn.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.AckBtn.setObjectName("AckBtn")
        self.playerOne = QtWidgets.QFrame(Dialog)
        self.playerOne.setGeometry(QtCore.QRect(19, 80, 471, 81))
        self.playerOne.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerOne.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerOne.setObjectName("playerOne")
        self.label_2 = QtWidgets.QLabel(self.playerOne)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.playerOneText = QtWidgets.QPlainTextEdit(self.playerOne)
        self.playerOneText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerOneText.setObjectName("playerOneText")
        self.playerOneaddBtn = QtWidgets.QPushButton(self.playerOne)
        self.playerOneaddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerOneaddBtn.setObjectName("playerOneaddBtn")
        self.playerOneClearBtn = QtWidgets.QPushButton(self.playerOne)
        self.playerOneClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerOneClearBtn.setObjectName("playerOneClearBtn")
        self.playerTow = QtWidgets.QFrame(Dialog)
        self.playerTow.setGeometry(QtCore.QRect(20, 180, 471, 81))
        self.playerTow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerTow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerTow.setObjectName("playerTow")
        self.label_3 = QtWidgets.QLabel(self.playerTow)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_3.setObjectName("label_3")
        self.playerTowText = QtWidgets.QPlainTextEdit(self.playerTow)
        self.playerTowText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerTowText.setObjectName("playerTowText")
        self.playerTowaddBtn = QtWidgets.QPushButton(self.playerTow)
        self.playerTowaddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerTowaddBtn.setObjectName("playerTowaddBtn")
        self.playerTowClearBtn = QtWidgets.QPushButton(self.playerTow)
        self.playerTowClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerTowClearBtn.setObjectName("playerTowClearBtn")
        self.playerThree = QtWidgets.QFrame(Dialog)
        self.playerThree.setGeometry(QtCore.QRect(20, 280, 471, 81))
        self.playerThree.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerThree.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerThree.setObjectName("playerThree")
        self.label_4 = QtWidgets.QLabel(self.playerThree)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_4.setObjectName("label_4")
        self.playerThreeText = QtWidgets.QPlainTextEdit(self.playerThree)
        self.playerThreeText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerThreeText.setObjectName("playerThreeText")
        self.playerThreeaddBtn = QtWidgets.QPushButton(self.playerThree)
        self.playerThreeaddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerThreeaddBtn.setObjectName("playerThreeaddBtn")
        self.playerThreeClearBtn = QtWidgets.QPushButton(self.playerThree)
        self.playerThreeClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerThreeClearBtn.setObjectName("playerThreeClearBtn")
        self.playerFour = QtWidgets.QFrame(Dialog)
        self.playerFour.setGeometry(QtCore.QRect(20, 380, 471, 81))
        self.playerFour.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerFour.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerFour.setObjectName("playerFour")
        self.label_5 = QtWidgets.QLabel(self.playerFour)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_5.setObjectName("label_5")
        self.playerFourText = QtWidgets.QPlainTextEdit(self.playerFour)
        self.playerFourText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerFourText.setObjectName("playerFourText")
        self.playerFouraddBtn = QtWidgets.QPushButton(self.playerFour)
        self.playerFouraddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerFouraddBtn.setObjectName("playerFouraddBtn")
        self.playerFourClearBtn = QtWidgets.QPushButton(self.playerFour)
        self.playerFourClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerFourClearBtn.setObjectName("playerFourClearBtn")
        self.ultimateBtn = QtWidgets.QPushButton(Dialog)
        self.ultimateBtn.setGeometry(QtCore.QRect(490, 640, 151, 51))
        self.ultimateBtn.setObjectName("ultimateBtn")
        self.dunCard = QtWidgets.QFrame(Dialog)
        self.dunCard.setGeometry(QtCore.QRect(20, 480, 471, 81))
        self.dunCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dunCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dunCard.setObjectName("dunCard")
        self.label_7 = QtWidgets.QLabel(self.dunCard)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_7.setObjectName("label_7")
        self.dunText = QtWidgets.QPlainTextEdit(self.dunCard)
        self.dunText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.dunText.setObjectName("dunText")
        self.dunAddCard = QtWidgets.QPushButton(self.dunCard)
        self.dunAddCard.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.dunAddCard.setObjectName("dunAddCard")
        self.dunClear = QtWidgets.QPushButton(self.dunCard)
        self.dunClear.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.dunClear.setObjectName("dunClear")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(510, 60, 511, 501))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 22, 77, 111))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1B = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_1B.setObjectName("label_1B")
        self.verticalLayout.addWidget(self.label_1B)
        self.pushButton_1B = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_1B.setObjectName("pushButton_1B")
        self.verticalLayout.addWidget(self.pushButton_1B)
        self.label_2B = QtWidgets.QLabel(self.groupBox)
        self.label_2B.setGeometry(QtCore.QRect(110, 24, 69, 80))
        self.label_2B.setObjectName("label_2B")
        self.pushButton_2B = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2B.setGeometry(QtCore.QRect(110, 110, 69, 23))
        self.pushButton_2B.setObjectName("pushButton_2B")
        self.label_3B = QtWidgets.QLabel(self.groupBox)
        self.label_3B.setGeometry(QtCore.QRect(210, 24, 69, 80))
        self.label_3B.setObjectName("label_3B")
        self.pushButton_3B = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3B.setGeometry(QtCore.QRect(210, 110, 69, 23))
        self.pushButton_3B.setObjectName("pushButton_3B")
        self.label_4B = QtWidgets.QLabel(self.groupBox)
        self.label_4B.setGeometry(QtCore.QRect(310, 24, 69, 80))
        self.label_4B.setObjectName("label_4B")
        self.pushButton_4B = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4B.setGeometry(QtCore.QRect(310, 110, 69, 23))
        self.pushButton_4B.setObjectName("pushButton_4B")
        self.label_5B = QtWidgets.QLabel(self.groupBox)
        self.label_5B.setGeometry(QtCore.QRect(410, 24, 69, 80))
        self.label_5B.setObjectName("label_5B")
        self.pushButton_5B = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5B.setGeometry(QtCore.QRect(410, 110, 69, 23))
        self.pushButton_5B.setObjectName("pushButton_5B")
        self.label_6B = QtWidgets.QLabel(self.groupBox)
        self.label_6B.setGeometry(QtCore.QRect(10, 134, 69, 80))
        self.label_6B.setObjectName("label_6B")
        self.pushButton_6B = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6B.setGeometry(QtCore.QRect(10, 220, 69, 23))
        self.pushButton_6B.setObjectName("pushButton_6B")
        self.label_7B = QtWidgets.QLabel(self.groupBox)
        self.label_7B.setGeometry(QtCore.QRect(110, 134, 69, 80))
        self.label_7B.setObjectName("label_7B")
        self.pushButton_7B = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7B.setGeometry(QtCore.QRect(110, 220, 69, 23))
        self.pushButton_7B.setObjectName("pushButton_7B")
        self.label_8B = QtWidgets.QLabel(self.groupBox)
        self.label_8B.setGeometry(QtCore.QRect(210, 134, 69, 80))
        self.label_8B.setObjectName("label_8B")
        self.pushButton_8B = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8B.setGeometry(QtCore.QRect(210, 220, 69, 23))
        self.pushButton_8B.setObjectName("pushButton_8B")
        self.label_9B = QtWidgets.QLabel(self.groupBox)
        self.label_9B.setGeometry(QtCore.QRect(310, 134, 69, 80))
        self.label_9B.setObjectName("label_9B")
        self.pushButton_9B = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9B.setGeometry(QtCore.QRect(310, 220, 69, 23))
        self.pushButton_9B.setObjectName("pushButton_9B")
        self.label_TB = QtWidgets.QLabel(self.groupBox)
        self.label_TB.setGeometry(QtCore.QRect(410, 134, 69, 80))
        self.label_TB.setObjectName("label_TB")
        self.pushButton_TB = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_TB.setGeometry(QtCore.QRect(410, 220, 69, 23))
        self.pushButton_TB.setObjectName("pushButton_TB")
        self.pushButton_1S = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_1S.setGeometry(QtCore.QRect(10, 346, 69, 23))
        self.pushButton_1S.setObjectName("pushButton_1S")
        self.label_1S = QtWidgets.QLabel(self.groupBox)
        self.label_1S.setGeometry(QtCore.QRect(10, 260, 69, 80))
        self.label_1S.setObjectName("label_1S")
        self.pushButton_2S = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2S.setGeometry(QtCore.QRect(110, 346, 69, 23))
        self.pushButton_2S.setObjectName("pushButton_2S")
        self.label_2S = QtWidgets.QLabel(self.groupBox)
        self.label_2S.setGeometry(QtCore.QRect(110, 260, 69, 80))
        self.label_2S.setObjectName("label_2S")
        self.pushButton_3S = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3S.setGeometry(QtCore.QRect(210, 346, 69, 23))
        self.pushButton_3S.setObjectName("pushButton_3S")
        self.label_3S = QtWidgets.QLabel(self.groupBox)
        self.label_3S.setGeometry(QtCore.QRect(210, 260, 69, 80))
        self.label_3S.setObjectName("label_3S")
        self.pushButton_4S = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4S.setGeometry(QtCore.QRect(310, 346, 69, 23))
        self.pushButton_4S.setObjectName("pushButton_4S")
        self.label_4S = QtWidgets.QLabel(self.groupBox)
        self.label_4S.setGeometry(QtCore.QRect(310, 260, 69, 80))
        self.label_4S.setObjectName("label_4S")
        self.pushButton_5S = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5S.setGeometry(QtCore.QRect(410, 346, 69, 23))
        self.pushButton_5S.setObjectName("pushButton_5S")
        self.label_5S = QtWidgets.QLabel(self.groupBox)
        self.label_5S.setGeometry(QtCore.QRect(410, 260, 69, 80))
        self.label_5S.setObjectName("label_5S")
        self.label_8S = QtWidgets.QLabel(self.groupBox)
        self.label_8S.setGeometry(QtCore.QRect(210, 374, 69, 80))
        self.label_8S.setObjectName("label_8S")
        self.label_TS = QtWidgets.QLabel(self.groupBox)
        self.label_TS.setGeometry(QtCore.QRect(410, 374, 69, 80))
        self.label_TS.setObjectName("label_TS")
        self.label_7S = QtWidgets.QLabel(self.groupBox)
        self.label_7S.setGeometry(QtCore.QRect(110, 374, 69, 80))
        self.label_7S.setObjectName("label_7S")
        self.pushButton_6S = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6S.setGeometry(QtCore.QRect(10, 460, 69, 23))
        self.pushButton_6S.setObjectName("pushButton_6S")
        self.pushButton_8S = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8S.setGeometry(QtCore.QRect(210, 460, 69, 23))
        self.pushButton_8S.setObjectName("pushButton_8S")
        self.pushButton_9S = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9S.setGeometry(QtCore.QRect(310, 460, 69, 23))
        self.pushButton_9S.setObjectName("pushButton_9S")
        self.pushButton_7S = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7S.setGeometry(QtCore.QRect(110, 460, 69, 23))
        self.pushButton_7S.setObjectName("pushButton_7S")
        self.label_6S = QtWidgets.QLabel(self.groupBox)
        self.label_6S.setGeometry(QtCore.QRect(10, 374, 69, 80))
        self.label_6S.setObjectName("label_6S")
        self.label_9S = QtWidgets.QLabel(self.groupBox)
        self.label_9S.setGeometry(QtCore.QRect(310, 374, 69, 80))
        self.label_9S.setObjectName("label_9S")
        self.pushButton_TS = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_TS.setGeometry(QtCore.QRect(410, 460, 69, 23))
        self.pushButton_TS.setObjectName("pushButton_TS")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "游戏人数"))
        self.comboBox.setItemText(0, _translate("Dialog", "2"))
        self.comboBox.setItemText(1, _translate("Dialog", "3"))
        self.comboBox.setItemText(2, _translate("Dialog", "4"))
        self.AckBtn.setText(_translate("Dialog", "确认"))
        self.label_2.setText(_translate("Dialog", "玩家一"))
        self.playerOneaddBtn.setText(_translate("Dialog", "添加"))
        self.playerOneClearBtn.setText(_translate("Dialog", "重置"))
        self.label_3.setText(_translate("Dialog", "玩家二"))
        self.playerTowaddBtn.setText(_translate("Dialog", "添加"))
        self.playerTowClearBtn.setText(_translate("Dialog", "重置"))
        self.label_4.setText(_translate("Dialog", "玩家三"))
        self.playerThreeaddBtn.setText(_translate("Dialog", "添加"))
        self.playerThreeClearBtn.setText(_translate("Dialog", "重置"))
        self.label_5.setText(_translate("Dialog", "玩家四"))
        self.playerFouraddBtn.setText(_translate("Dialog", "添加"))
        self.playerFourClearBtn.setText(_translate("Dialog", "重置"))
        self.ultimateBtn.setText(_translate("Dialog", "保  存"))
        self.label_7.setText(_translate("Dialog", "墩上牌数据"))
        self.dunAddCard.setText(_translate("Dialog", "添加"))
        self.dunClear.setText(_translate("Dialog", "重置"))
        self.groupBox.setTitle(_translate("Dialog", "牌型列表"))
        self.label_1B.setText(_translate("Dialog", "1B"))
        self.pushButton_1B.setText(_translate("Dialog", "+"))
        self.label_2B.setText(_translate("Dialog", "2B"))
        self.pushButton_2B.setText(_translate("Dialog", "+"))
        self.label_3B.setText(_translate("Dialog", "3B"))
        self.pushButton_3B.setText(_translate("Dialog", "+"))
        self.label_4B.setText(_translate("Dialog", "4B"))
        self.pushButton_4B.setText(_translate("Dialog", "+"))
        self.label_5B.setText(_translate("Dialog", "5B"))
        self.pushButton_5B.setText(_translate("Dialog", "+"))
        self.label_6B.setText(_translate("Dialog", "6B"))
        self.pushButton_6B.setText(_translate("Dialog", "+"))
        self.label_7B.setText(_translate("Dialog", "7B"))
        self.pushButton_7B.setText(_translate("Dialog", "+"))
        self.label_8B.setText(_translate("Dialog", "8B"))
        self.pushButton_8B.setText(_translate("Dialog", "+"))
        self.label_9B.setText(_translate("Dialog", "9B"))
        self.pushButton_9B.setText(_translate("Dialog", "+"))
        self.label_TB.setText(_translate("Dialog", "TB"))
        self.pushButton_TB.setText(_translate("Dialog", "+"))
        self.pushButton_1S.setText(_translate("Dialog", "+"))
        self.label_1S.setText(_translate("Dialog", "1S"))
        self.pushButton_2S.setText(_translate("Dialog", "+"))
        self.label_2S.setText(_translate("Dialog", "2S"))
        self.pushButton_3S.setText(_translate("Dialog", "+"))
        self.label_3S.setText(_translate("Dialog", "3S"))
        self.pushButton_4S.setText(_translate("Dialog", "+"))
        self.label_4S.setText(_translate("Dialog", "4S"))
        self.pushButton_5S.setText(_translate("Dialog", "+"))
        self.label_5S.setText(_translate("Dialog", "5S"))
        self.label_8S.setText(_translate("Dialog", "8S"))
        self.label_TS.setText(_translate("Dialog", "TS"))
        self.label_7S.setText(_translate("Dialog", "7S"))
        self.pushButton_6S.setText(_translate("Dialog", "+"))
        self.pushButton_8S.setText(_translate("Dialog", "+"))
        self.pushButton_9S.setText(_translate("Dialog", "+"))
        self.pushButton_7S.setText(_translate("Dialog", "+"))
        self.label_6S.setText(_translate("Dialog", "6S"))
        self.label_9S.setText(_translate("Dialog", "9S"))
        self.pushButton_TS.setText(_translate("Dialog", "+"))

