# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'runFast.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1419, 985)
        self.playerTow = QtWidgets.QFrame(Dialog)
        self.playerTow.setGeometry(QtCore.QRect(10, 160, 471, 81))
        self.playerTow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerTow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerTow.setObjectName("playerTow")
        self.label_3 = QtWidgets.QLabel(self.playerTow)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_3.setObjectName("label_3")
        self.playerTowText = QtWidgets.QPlainTextEdit(self.playerTow)
        self.playerTowText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerTowText.setObjectName("playerTowText")
        self.playerTowaddBtn = QtWidgets.QPushButton(self.playerTow)
        self.playerTowaddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerTowaddBtn.setObjectName("playerTowaddBtn")
        self.playerTowClearBtn = QtWidgets.QPushButton(self.playerTow)
        self.playerTowClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerTowClearBtn.setObjectName("playerTowClearBtn")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.playerOne = QtWidgets.QFrame(Dialog)
        self.playerOne.setGeometry(QtCore.QRect(10, 60, 471, 81))
        self.playerOne.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerOne.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerOne.setObjectName("playerOne")
        self.label_2 = QtWidgets.QLabel(self.playerOne)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.playerOneText = QtWidgets.QPlainTextEdit(self.playerOne)
        self.playerOneText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerOneText.setObjectName("playerOneText")
        self.playerOneaddBtn = QtWidgets.QPushButton(self.playerOne)
        self.playerOneaddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerOneaddBtn.setObjectName("playerOneaddBtn")
        self.playerOneClearBtn = QtWidgets.QPushButton(self.playerOne)
        self.playerOneClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerOneClearBtn.setObjectName("playerOneClearBtn")
        self.dunCard = QtWidgets.QFrame(Dialog)
        self.dunCard.setGeometry(QtCore.QRect(10, 360, 471, 81))
        self.dunCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dunCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dunCard.setObjectName("dunCard")
        self.label_7 = QtWidgets.QLabel(self.dunCard)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_7.setObjectName("label_7")
        self.dunText = QtWidgets.QPlainTextEdit(self.dunCard)
        self.dunText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.dunText.setObjectName("dunText")
        self.dunAddCard = QtWidgets.QPushButton(self.dunCard)
        self.dunAddCard.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.dunAddCard.setObjectName("dunAddCard")
        self.dunClear = QtWidgets.QPushButton(self.dunCard)
        self.dunClear.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.dunClear.setObjectName("dunClear")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 88, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.playerComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.playerComboBox.setObjectName("playerComboBox")
        self.playerComboBox.addItem("")
        self.playerComboBox.addItem("")
        self.horizontalLayout.addWidget(self.playerComboBox)
        self.saveBtn = QtWidgets.QPushButton(Dialog)
        self.saveBtn.setGeometry(QtCore.QRect(200, 650, 161, 51))
        self.saveBtn.setObjectName("saveBtn")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(540, 40, 811, 891))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 22, 77, 111))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_R1 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_R1.setObjectName("label_R1")
        self.verticalLayout.addWidget(self.label_R1)
        self.pushButton_R1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_R1.setObjectName("pushButton_R1")
        self.verticalLayout.addWidget(self.pushButton_R1)
        self.label_R2 = QtWidgets.QLabel(self.groupBox)
        self.label_R2.setGeometry(QtCore.QRect(110, 24, 69, 80))
        self.label_R2.setObjectName("label_R2")
        self.pushButton_R2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R2.setGeometry(QtCore.QRect(110, 110, 69, 23))
        self.pushButton_R2.setObjectName("pushButton_R2")
        self.label_R3 = QtWidgets.QLabel(self.groupBox)
        self.label_R3.setGeometry(QtCore.QRect(210, 24, 69, 80))
        self.label_R3.setObjectName("label_R3")
        self.pushButton_R3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R3.setGeometry(QtCore.QRect(210, 110, 69, 23))
        self.pushButton_R3.setObjectName("pushButton_R3")
        self.label_R4 = QtWidgets.QLabel(self.groupBox)
        self.label_R4.setGeometry(QtCore.QRect(310, 24, 69, 80))
        self.label_R4.setObjectName("label_R4")
        self.pushButton_R4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R4.setGeometry(QtCore.QRect(310, 110, 69, 23))
        self.pushButton_R4.setObjectName("pushButton_R4")
        self.label_R5 = QtWidgets.QLabel(self.groupBox)
        self.label_R5.setGeometry(QtCore.QRect(410, 24, 69, 80))
        self.label_R5.setObjectName("label_R5")
        self.pushButton_R5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R5.setGeometry(QtCore.QRect(410, 110, 69, 23))
        self.pushButton_R5.setObjectName("pushButton_R5")
        self.label_R6 = QtWidgets.QLabel(self.groupBox)
        self.label_R6.setGeometry(QtCore.QRect(510, 24, 69, 80))
        self.label_R6.setObjectName("label_R6")
        self.pushButton_R6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R6.setGeometry(QtCore.QRect(510, 110, 69, 23))
        self.pushButton_R6.setObjectName("pushButton_R6")
        self.label_R7 = QtWidgets.QLabel(self.groupBox)
        self.label_R7.setGeometry(QtCore.QRect(610, 24, 69, 80))
        self.label_R7.setObjectName("label_R7")
        self.pushButton_R7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R7.setGeometry(QtCore.QRect(610, 110, 69, 23))
        self.pushButton_R7.setObjectName("pushButton_R7")
        self.label_R9 = QtWidgets.QLabel(self.groupBox)
        self.label_R9.setGeometry(QtCore.QRect(10, 134, 69, 80))
        self.label_R9.setObjectName("label_R9")
        self.pushButton_R9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R9.setGeometry(QtCore.QRect(10, 220, 69, 23))
        self.pushButton_R9.setObjectName("pushButton_R9")
        self.label_R10 = QtWidgets.QLabel(self.groupBox)
        self.label_R10.setGeometry(QtCore.QRect(110, 134, 69, 80))
        self.label_R10.setObjectName("label_R10")
        self.pushButton_R10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R10.setGeometry(QtCore.QRect(110, 220, 69, 23))
        self.pushButton_R10.setObjectName("pushButton_R10")
        self.label_R11 = QtWidgets.QLabel(self.groupBox)
        self.label_R11.setGeometry(QtCore.QRect(210, 134, 69, 80))
        self.label_R11.setObjectName("label_R11")
        self.pushButton_R11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R11.setGeometry(QtCore.QRect(210, 220, 69, 23))
        self.pushButton_R11.setObjectName("pushButton_R11")
        self.label_R12 = QtWidgets.QLabel(self.groupBox)
        self.label_R12.setGeometry(QtCore.QRect(310, 134, 69, 80))
        self.label_R12.setObjectName("label_R12")
        self.pushButton_R12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R12.setGeometry(QtCore.QRect(310, 220, 69, 23))
        self.pushButton_R12.setObjectName("pushButton_R12")
        self.label_R13 = QtWidgets.QLabel(self.groupBox)
        self.label_R13.setGeometry(QtCore.QRect(410, 134, 69, 80))
        self.label_R13.setObjectName("label_R13")
        self.pushButton_R13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R13.setGeometry(QtCore.QRect(410, 220, 69, 23))
        self.pushButton_R13.setObjectName("pushButton_R13")
        self.label_B1 = QtWidgets.QLabel(self.groupBox)
        self.label_B1.setGeometry(QtCore.QRect(510, 134, 69, 80))
        self.label_B1.setObjectName("label_B1")
        self.pushButton_B1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B1.setGeometry(QtCore.QRect(510, 220, 69, 23))
        self.pushButton_B1.setObjectName("pushButton_B1")
        self.label_B2 = QtWidgets.QLabel(self.groupBox)
        self.label_B2.setGeometry(QtCore.QRect(610, 134, 69, 80))
        self.label_B2.setObjectName("label_B2")
        self.pushButton_B2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B2.setGeometry(QtCore.QRect(610, 220, 69, 23))
        self.pushButton_B2.setObjectName("pushButton_B2")
        self.pushButton_B4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B4.setGeometry(QtCore.QRect(10, 346, 69, 23))
        self.pushButton_B4.setObjectName("pushButton_B4")
        self.label_B4 = QtWidgets.QLabel(self.groupBox)
        self.label_B4.setGeometry(QtCore.QRect(10, 260, 69, 80))
        self.label_B4.setObjectName("label_B4")
        self.pushButton_B5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B5.setGeometry(QtCore.QRect(110, 346, 69, 23))
        self.pushButton_B5.setObjectName("pushButton_B5")
        self.label_B5 = QtWidgets.QLabel(self.groupBox)
        self.label_B5.setGeometry(QtCore.QRect(110, 260, 69, 80))
        self.label_B5.setObjectName("label_B5")
        self.pushButton_B6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B6.setGeometry(QtCore.QRect(210, 346, 69, 23))
        self.pushButton_B6.setObjectName("pushButton_B6")
        self.label_B6 = QtWidgets.QLabel(self.groupBox)
        self.label_B6.setGeometry(QtCore.QRect(210, 260, 69, 80))
        self.label_B6.setObjectName("label_B6")
        self.pushButton_B7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B7.setGeometry(QtCore.QRect(310, 346, 69, 23))
        self.pushButton_B7.setObjectName("pushButton_B7")
        self.label_B7 = QtWidgets.QLabel(self.groupBox)
        self.label_B7.setGeometry(QtCore.QRect(310, 260, 69, 80))
        self.label_B7.setObjectName("label_B7")
        self.label_B8 = QtWidgets.QLabel(self.groupBox)
        self.label_B8.setGeometry(QtCore.QRect(410, 260, 69, 80))
        self.label_B8.setObjectName("label_B8")
        self.pushButton_B8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B8.setGeometry(QtCore.QRect(410, 346, 69, 23))
        self.pushButton_B8.setObjectName("pushButton_B8")
        self.pushButton_B9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B9.setGeometry(QtCore.QRect(510, 346, 69, 23))
        self.pushButton_B9.setObjectName("pushButton_B9")
        self.label_B9 = QtWidgets.QLabel(self.groupBox)
        self.label_B9.setGeometry(QtCore.QRect(510, 260, 69, 80))
        self.label_B9.setObjectName("label_B9")
        self.pushButton_B10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B10.setGeometry(QtCore.QRect(610, 346, 69, 23))
        self.pushButton_B10.setObjectName("pushButton_B10")
        self.label_B10 = QtWidgets.QLabel(self.groupBox)
        self.label_B10.setGeometry(QtCore.QRect(610, 260, 69, 80))
        self.label_B10.setObjectName("label_B10")
        self.pushButton_B11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B11.setGeometry(QtCore.QRect(710, 346, 69, 23))
        self.pushButton_B11.setObjectName("pushButton_B11")
        self.label_B11 = QtWidgets.QLabel(self.groupBox)
        self.label_B11.setGeometry(QtCore.QRect(710, 260, 69, 80))
        self.label_B11.setObjectName("label_B11")
        self.pushButton_B12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B12.setGeometry(QtCore.QRect(10, 476, 69, 23))
        self.pushButton_B12.setObjectName("pushButton_B12")
        self.label_B12 = QtWidgets.QLabel(self.groupBox)
        self.label_B12.setGeometry(QtCore.QRect(10, 390, 69, 80))
        self.label_B12.setObjectName("label_B12")
        self.pushButton_B13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B13.setGeometry(QtCore.QRect(110, 476, 69, 23))
        self.pushButton_B13.setObjectName("pushButton_B13")
        self.label_B13 = QtWidgets.QLabel(self.groupBox)
        self.label_B13.setGeometry(QtCore.QRect(110, 390, 69, 80))
        self.label_B13.setObjectName("label_B13")
        self.label_C1 = QtWidgets.QLabel(self.groupBox)
        self.label_C1.setGeometry(QtCore.QRect(210, 390, 69, 80))
        self.label_C1.setObjectName("label_C1")
        self.pushButton_C1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C1.setGeometry(QtCore.QRect(210, 476, 69, 23))
        self.pushButton_C1.setObjectName("pushButton_C1")
        self.pushButton_C2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C2.setGeometry(QtCore.QRect(310, 476, 69, 23))
        self.pushButton_C2.setObjectName("pushButton_C2")
        self.label_C2 = QtWidgets.QLabel(self.groupBox)
        self.label_C2.setGeometry(QtCore.QRect(310, 390, 69, 80))
        self.label_C2.setObjectName("label_C2")
        self.label_C3 = QtWidgets.QLabel(self.groupBox)
        self.label_C3.setGeometry(QtCore.QRect(410, 390, 69, 80))
        self.label_C3.setObjectName("label_C3")
        self.pushButton_C3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C3.setGeometry(QtCore.QRect(410, 476, 69, 23))
        self.pushButton_C3.setObjectName("pushButton_C3")
        self.pushButton_C6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C6.setGeometry(QtCore.QRect(710, 476, 69, 23))
        self.pushButton_C6.setObjectName("pushButton_C6")
        self.label_C6 = QtWidgets.QLabel(self.groupBox)
        self.label_C6.setGeometry(QtCore.QRect(710, 390, 69, 80))
        self.label_C6.setObjectName("label_C6")
        self.pushButton_C7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C7.setGeometry(QtCore.QRect(10, 606, 69, 23))
        self.pushButton_C7.setObjectName("pushButton_C7")
        self.label_C7 = QtWidgets.QLabel(self.groupBox)
        self.label_C7.setGeometry(QtCore.QRect(10, 520, 69, 80))
        self.label_C7.setObjectName("label_C7")
        self.label_C8 = QtWidgets.QLabel(self.groupBox)
        self.label_C8.setGeometry(QtCore.QRect(110, 520, 69, 80))
        self.label_C8.setObjectName("label_C8")
        self.pushButton_C8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C8.setGeometry(QtCore.QRect(110, 606, 69, 23))
        self.pushButton_C8.setObjectName("pushButton_C8")
        self.pushButton_C9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C9.setGeometry(QtCore.QRect(210, 606, 69, 23))
        self.pushButton_C9.setObjectName("pushButton_C9")
        self.label_C9 = QtWidgets.QLabel(self.groupBox)
        self.label_C9.setGeometry(QtCore.QRect(210, 520, 69, 80))
        self.label_C9.setObjectName("label_C9")
        self.pushButton_C10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C10.setGeometry(QtCore.QRect(310, 606, 69, 23))
        self.pushButton_C10.setObjectName("pushButton_C10")
        self.label_C10 = QtWidgets.QLabel(self.groupBox)
        self.label_C10.setGeometry(QtCore.QRect(310, 520, 69, 80))
        self.label_C10.setObjectName("label_C10")
        self.pushButton_C11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C11.setGeometry(QtCore.QRect(410, 606, 69, 23))
        self.pushButton_C11.setObjectName("pushButton_C11")
        self.label_C11 = QtWidgets.QLabel(self.groupBox)
        self.label_C11.setGeometry(QtCore.QRect(410, 520, 69, 80))
        self.label_C11.setObjectName("label_C11")
        self.pushButton_R8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_R8.setGeometry(QtCore.QRect(710, 110, 69, 23))
        self.pushButton_R8.setObjectName("pushButton_R8")
        self.label_R8 = QtWidgets.QLabel(self.groupBox)
        self.label_R8.setGeometry(QtCore.QRect(710, 24, 69, 80))
        self.label_R8.setObjectName("label_R8")
        self.label_B3 = QtWidgets.QLabel(self.groupBox)
        self.label_B3.setGeometry(QtCore.QRect(710, 134, 69, 80))
        self.label_B3.setObjectName("label_B3")
        self.pushButton_B3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_B3.setGeometry(QtCore.QRect(710, 220, 69, 23))
        self.pushButton_B3.setObjectName("pushButton_B3")
        self.label_C4 = QtWidgets.QLabel(self.groupBox)
        self.label_C4.setGeometry(QtCore.QRect(510, 390, 69, 80))
        self.label_C4.setObjectName("label_C4")
        self.label_C5 = QtWidgets.QLabel(self.groupBox)
        self.label_C5.setGeometry(QtCore.QRect(610, 390, 69, 80))
        self.label_C5.setObjectName("label_C5")
        self.pushButton_C5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C5.setGeometry(QtCore.QRect(610, 476, 69, 23))
        self.pushButton_C5.setObjectName("pushButton_C5")
        self.pushButtonC4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonC4.setGeometry(QtCore.QRect(510, 476, 69, 23))
        self.pushButtonC4.setObjectName("pushButtonC4")
        self.pushButton_C13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C13.setGeometry(QtCore.QRect(610, 606, 69, 23))
        self.pushButton_C13.setObjectName("pushButton_C13")
        self.label_C13 = QtWidgets.QLabel(self.groupBox)
        self.label_C13.setGeometry(QtCore.QRect(610, 520, 69, 80))
        self.label_C13.setObjectName("label_C13")
        self.pushButton_C12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_C12.setGeometry(QtCore.QRect(510, 606, 69, 23))
        self.pushButton_C12.setObjectName("pushButton_C12")
        self.label_C12 = QtWidgets.QLabel(self.groupBox)
        self.label_C12.setGeometry(QtCore.QRect(510, 520, 69, 80))
        self.label_C12.setObjectName("label_C12")
        self.label_D5 = QtWidgets.QLabel(self.groupBox)
        self.label_D5.setGeometry(QtCore.QRect(310, 644, 69, 80))
        self.label_D5.setObjectName("label_D5")
        self.label_D7 = QtWidgets.QLabel(self.groupBox)
        self.label_D7.setGeometry(QtCore.QRect(510, 644, 69, 80))
        self.label_D7.setObjectName("label_D7")
        self.pushButtonD7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonD7.setGeometry(QtCore.QRect(510, 730, 69, 23))
        self.pushButtonD7.setObjectName("pushButtonD7")
        self.pushButton_D9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D9.setGeometry(QtCore.QRect(710, 730, 69, 23))
        self.pushButton_D9.setObjectName("pushButton_D9")
        self.label_D2 = QtWidgets.QLabel(self.groupBox)
        self.label_D2.setGeometry(QtCore.QRect(10, 644, 69, 80))
        self.label_D2.setObjectName("label_D2")
        self.label_D9 = QtWidgets.QLabel(self.groupBox)
        self.label_D9.setGeometry(QtCore.QRect(710, 644, 69, 80))
        self.label_D9.setObjectName("label_D9")
        self.pushButton_D8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D8.setGeometry(QtCore.QRect(610, 730, 69, 23))
        self.pushButton_D8.setObjectName("pushButton_D8")
        self.pushButton_D2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D2.setGeometry(QtCore.QRect(10, 730, 69, 23))
        self.pushButton_D2.setObjectName("pushButton_D2")
        self.pushButton_D3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D3.setGeometry(QtCore.QRect(110, 730, 69, 23))
        self.pushButton_D3.setObjectName("pushButton_D3")
        self.label_D6 = QtWidgets.QLabel(self.groupBox)
        self.label_D6.setGeometry(QtCore.QRect(410, 644, 69, 80))
        self.label_D6.setObjectName("label_D6")
        self.pushButton_D6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D6.setGeometry(QtCore.QRect(410, 730, 69, 23))
        self.pushButton_D6.setObjectName("pushButton_D6")
        self.pushButton_D5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D5.setGeometry(QtCore.QRect(310, 730, 69, 23))
        self.pushButton_D5.setObjectName("pushButton_D5")
        self.label_D4 = QtWidgets.QLabel(self.groupBox)
        self.label_D4.setGeometry(QtCore.QRect(210, 644, 69, 80))
        self.label_D4.setObjectName("label_D4")
        self.label_D3 = QtWidgets.QLabel(self.groupBox)
        self.label_D3.setGeometry(QtCore.QRect(110, 644, 69, 80))
        self.label_D3.setObjectName("label_D3")
        self.pushButton_D4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D4.setGeometry(QtCore.QRect(210, 730, 69, 23))
        self.pushButton_D4.setObjectName("pushButton_D4")
        self.label_D8 = QtWidgets.QLabel(self.groupBox)
        self.label_D8.setGeometry(QtCore.QRect(610, 644, 69, 80))
        self.label_D8.setObjectName("label_D8")
        self.label_D1 = QtWidgets.QLabel(self.groupBox)
        self.label_D1.setGeometry(QtCore.QRect(710, 520, 69, 80))
        self.label_D1.setObjectName("label_D1")
        self.pushButton_D1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D1.setGeometry(QtCore.QRect(710, 606, 69, 23))
        self.pushButton_D1.setObjectName("pushButton_D1")
        self.pushButton_D12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D12.setGeometry(QtCore.QRect(210, 860, 69, 23))
        self.pushButton_D12.setObjectName("pushButton_D12")
        self.label_D13 = QtWidgets.QLabel(self.groupBox)
        self.label_D13.setGeometry(QtCore.QRect(310, 774, 69, 80))
        self.label_D13.setObjectName("label_D13")
        self.label_D10 = QtWidgets.QLabel(self.groupBox)
        self.label_D10.setGeometry(QtCore.QRect(10, 774, 69, 80))
        self.label_D10.setObjectName("label_D10")
        self.pushButton_D13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D13.setGeometry(QtCore.QRect(310, 860, 69, 23))
        self.pushButton_D13.setObjectName("pushButton_D13")
        self.label_D11 = QtWidgets.QLabel(self.groupBox)
        self.label_D11.setGeometry(QtCore.QRect(110, 774, 69, 80))
        self.label_D11.setObjectName("label_D11")
        self.pushButton_D10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D10.setGeometry(QtCore.QRect(10, 860, 69, 23))
        self.pushButton_D10.setObjectName("pushButton_D10")
        self.pushButton_D11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_D11.setGeometry(QtCore.QRect(110, 860, 69, 23))
        self.pushButton_D11.setObjectName("pushButton_D11")
        self.label_D12 = QtWidgets.QLabel(self.groupBox)
        self.label_D12.setGeometry(QtCore.QRect(210, 774, 69, 80))
        self.label_D12.setObjectName("label_D12")
        self.playerThree = QtWidgets.QFrame(Dialog)
        self.playerThree.setGeometry(QtCore.QRect(10, 260, 471, 81))
        self.playerThree.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playerThree.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playerThree.setObjectName("playerThree")
        self.label_4 = QtWidgets.QLabel(self.playerThree)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_4.setObjectName("label_4")
        self.playerThreeText = QtWidgets.QPlainTextEdit(self.playerThree)
        self.playerThreeText.setGeometry(QtCore.QRect(10, 30, 351, 41))
        self.playerThreeText.setObjectName("playerThreeText")
        self.playerThreeaddBtn = QtWidgets.QPushButton(self.playerThree)
        self.playerThreeaddBtn.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.playerThreeaddBtn.setObjectName("playerThreeaddBtn")
        self.playerThreeClearBtn = QtWidgets.QPushButton(self.playerThree)
        self.playerThreeClearBtn.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.playerThreeClearBtn.setObjectName("playerThreeClearBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "玩家二"))
        self.playerTowaddBtn.setText(_translate("Dialog", "添加"))
        self.playerTowClearBtn.setText(_translate("Dialog", "重置"))
        self.pushButton.setText(_translate("Dialog", "确认"))
        self.label_2.setText(_translate("Dialog", "玩家一"))
        self.playerOneaddBtn.setText(_translate("Dialog", "添加"))
        self.playerOneClearBtn.setText(_translate("Dialog", "重置"))
        self.label_7.setText(_translate("Dialog", "墩上牌数据"))
        self.dunAddCard.setText(_translate("Dialog", "添加"))
        self.dunClear.setText(_translate("Dialog", "重置"))
        self.label.setText(_translate("Dialog", "游戏人数"))
        self.playerComboBox.setItemText(0, _translate("Dialog", "3"))
        self.playerComboBox.setItemText(1, _translate("Dialog", "2"))
        self.saveBtn.setText(_translate("Dialog", "保   存"))
        self.groupBox.setTitle(_translate("Dialog", "牌型列表"))
        self.label_R1.setText(_translate("Dialog", "R1"))
        self.pushButton_R1.setText(_translate("Dialog", "+"))
        self.label_R2.setText(_translate("Dialog", "R2"))
        self.pushButton_R2.setText(_translate("Dialog", "+"))
        self.label_R3.setText(_translate("Dialog", "R3"))
        self.pushButton_R3.setText(_translate("Dialog", "+"))
        self.label_R4.setText(_translate("Dialog", "R4"))
        self.pushButton_R4.setText(_translate("Dialog", "+"))
        self.label_R5.setText(_translate("Dialog", "R5"))
        self.pushButton_R5.setText(_translate("Dialog", "+"))
        self.label_R6.setText(_translate("Dialog", "R6"))
        self.pushButton_R6.setText(_translate("Dialog", "+"))
        self.label_R7.setText(_translate("Dialog", "R7"))
        self.pushButton_R7.setText(_translate("Dialog", "+"))
        self.label_R9.setText(_translate("Dialog", "R9"))
        self.pushButton_R9.setText(_translate("Dialog", "+"))
        self.label_R10.setText(_translate("Dialog", "R10"))
        self.pushButton_R10.setText(_translate("Dialog", "+"))
        self.label_R11.setText(_translate("Dialog", "R11"))
        self.pushButton_R11.setText(_translate("Dialog", "+"))
        self.label_R12.setText(_translate("Dialog", "R12"))
        self.pushButton_R12.setText(_translate("Dialog", "+"))
        self.label_R13.setText(_translate("Dialog", "R13"))
        self.pushButton_R13.setText(_translate("Dialog", "+"))
        self.label_B1.setText(_translate("Dialog", "B1"))
        self.pushButton_B1.setText(_translate("Dialog", "+"))
        self.label_B2.setText(_translate("Dialog", "B2"))
        self.pushButton_B2.setText(_translate("Dialog", "+"))
        self.pushButton_B4.setText(_translate("Dialog", "+"))
        self.label_B4.setText(_translate("Dialog", "B4"))
        self.pushButton_B5.setText(_translate("Dialog", "+"))
        self.label_B5.setText(_translate("Dialog", "B5"))
        self.pushButton_B6.setText(_translate("Dialog", "+"))
        self.label_B6.setText(_translate("Dialog", "B6"))
        self.pushButton_B7.setText(_translate("Dialog", "+"))
        self.label_B7.setText(_translate("Dialog", "B7"))
        self.label_B8.setText(_translate("Dialog", "B8"))
        self.pushButton_B8.setText(_translate("Dialog", "+"))
        self.pushButton_B9.setText(_translate("Dialog", "+"))
        self.label_B9.setText(_translate("Dialog", "B9"))
        self.pushButton_B10.setText(_translate("Dialog", "+"))
        self.label_B10.setText(_translate("Dialog", "B10"))
        self.pushButton_B11.setText(_translate("Dialog", "+"))
        self.label_B11.setText(_translate("Dialog", "B11"))
        self.pushButton_B12.setText(_translate("Dialog", "+"))
        self.label_B12.setText(_translate("Dialog", "B12"))
        self.pushButton_B13.setText(_translate("Dialog", "+"))
        self.label_B13.setText(_translate("Dialog", "B13"))
        self.label_C1.setText(_translate("Dialog", "C1"))
        self.pushButton_C1.setText(_translate("Dialog", "+"))
        self.pushButton_C2.setText(_translate("Dialog", "+"))
        self.label_C2.setText(_translate("Dialog", "C2"))
        self.label_C3.setText(_translate("Dialog", "C3"))
        self.pushButton_C3.setText(_translate("Dialog", "+"))
        self.pushButton_C6.setText(_translate("Dialog", "+"))
        self.label_C6.setText(_translate("Dialog", "C6"))
        self.pushButton_C7.setText(_translate("Dialog", "+"))
        self.label_C7.setText(_translate("Dialog", "C7"))
        self.label_C8.setText(_translate("Dialog", "C8"))
        self.pushButton_C8.setText(_translate("Dialog", "+"))
        self.pushButton_C9.setText(_translate("Dialog", "+"))
        self.label_C9.setText(_translate("Dialog", "C9"))
        self.pushButton_C10.setText(_translate("Dialog", "+"))
        self.label_C10.setText(_translate("Dialog", "C10"))
        self.pushButton_C11.setText(_translate("Dialog", "+"))
        self.label_C11.setText(_translate("Dialog", "C11"))
        self.pushButton_R8.setText(_translate("Dialog", "+"))
        self.label_R8.setText(_translate("Dialog", "R8"))
        self.label_B3.setText(_translate("Dialog", "B3"))
        self.pushButton_B3.setText(_translate("Dialog", "+"))
        self.label_C4.setText(_translate("Dialog", "C4"))
        self.label_C5.setText(_translate("Dialog", "C5"))
        self.pushButton_C5.setText(_translate("Dialog", "+"))
        self.pushButtonC4.setText(_translate("Dialog", "+"))
        self.pushButton_C13.setText(_translate("Dialog", "+"))
        self.label_C13.setText(_translate("Dialog", "C13"))
        self.pushButton_C12.setText(_translate("Dialog", "+"))
        self.label_C12.setText(_translate("Dialog", "C12"))
        self.label_D5.setText(_translate("Dialog", "D5"))
        self.label_D7.setText(_translate("Dialog", "D7"))
        self.pushButtonD7.setText(_translate("Dialog", "+"))
        self.pushButton_D9.setText(_translate("Dialog", "+"))
        self.label_D2.setText(_translate("Dialog", "D2"))
        self.label_D9.setText(_translate("Dialog", "D9"))
        self.pushButton_D8.setText(_translate("Dialog", "+"))
        self.pushButton_D2.setText(_translate("Dialog", "+"))
        self.pushButton_D3.setText(_translate("Dialog", "+"))
        self.label_D6.setText(_translate("Dialog", "D6"))
        self.pushButton_D6.setText(_translate("Dialog", "+"))
        self.pushButton_D5.setText(_translate("Dialog", "+"))
        self.label_D4.setText(_translate("Dialog", "D4"))
        self.label_D3.setText(_translate("Dialog", "D3"))
        self.pushButton_D4.setText(_translate("Dialog", "+"))
        self.label_D8.setText(_translate("Dialog", "D8"))
        self.label_D1.setText(_translate("Dialog", "D1"))
        self.pushButton_D1.setText(_translate("Dialog", "+"))
        self.pushButton_D12.setText(_translate("Dialog", "+"))
        self.label_D13.setText(_translate("Dialog", "D13"))
        self.label_D10.setText(_translate("Dialog", "D10"))
        self.pushButton_D13.setText(_translate("Dialog", "+"))
        self.label_D11.setText(_translate("Dialog", "D11"))
        self.pushButton_D10.setText(_translate("Dialog", "+"))
        self.pushButton_D11.setText(_translate("Dialog", "+"))
        self.label_D12.setText(_translate("Dialog", "D12"))
        self.label_4.setText(_translate("Dialog", "玩家三"))
        self.playerThreeaddBtn.setText(_translate("Dialog", "添加"))
        self.playerThreeClearBtn.setText(_translate("Dialog", "重置"))

